#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:50:00
#SBATCH -J quality_control
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se


# Load modules
module load bioinfo-tools
module load FastQC
# commands

fastqc -o /home/mama5390/genome_analysis/genome_analysis/out_files/fastqc_wgs /home/mama5390/genome_analysis/genome_analysis/raw_data/wgs/*
