#!/bin/bash -l

#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J annotation
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se

module load bioinfo-tools
module load braker/2.1.1_Perl5.24.1
module load augustus/3.2.3_Perl5.24.1
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.0
module load samtools/1.8
module load GeneMark/4.62-es

module load diamond
module load cdbfasta
module load perl_modules
module load biopython

export GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy

cd $HOME
source $AUGUSTUS_CONFIG_COPY
chmod a+w -R $HOME/augustus_config/species

export AUGUSTUS_CONFIG_PATH=$HOME/augustus_config
export AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin
export AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin/augustus

braker.pl --species=M.Natalensis --genome=$HOME/genome_analysis/data/raw_data/wgs/sel3_NW_015504249.fna --bam=$HOME/genome_analysis/genome_analysis/out_files/star_alignment/star_alignment_refAligned.sortedByCoord.out.bam
