#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 2:00:00
#SBATCH -J GenomeAnnotation_vers2
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se
#Modules
module load bioinfo-tools
module load braker/2.1.1_Perl5.24.1
module load augustus/3.2.3_Perl5.24.1
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.0
module load samtools/1.8
module load GeneMark/4.62-es
module load cdbfasta
module load diamond
module load perl_modules
module load biopython

export GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy
# Script
# Data retrival
ln -s /proj/g2021012/2_Eckalbar_2016/additional_data/sel3_NW_015503979.fna.gz $HOME/genome_analysis/data/raw_data/wgs/ref/
# Ran in home/mama5390 directory
cd $HOME
source $AUGUSTUS_CONFIG_COPY
chmod a+w -R /home/mama5390/augustus_config/species/
# cp -vf /sw/bioinfo/GeneMark/4.33-es/snowy/gm_key $HOME/.gm_key
gunzip -f $HOME/genome_analysis/data/raw_data/wgs/ref/sel3_NW_015503979.fna.gz
braker.pl --species=M_natalensis --useexisting --genome=$HOME/genome_analysis/data/raw_data/wgs/ref/sel3_NW_015503979.fna.gz --bam=$HOME/genome_analysis/genome_analysis/out_files/star_alignment/star_alignment_refAligned.sortedByCoord.out.bam --AUGUSTUS_CONFIG_PATH=/home/mama5390/augustus_config --AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin --AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/scripts --GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy


