#!/bin/bash -l

#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 2:00:00
#SBATCH -J GenomeAnnotation_vers2
#SBATCH --mail-type=ALL
#SBATCH --mail-user Matilda.Maxwell.5390@student.uu.se

#Modules
module load bioinfo-tools
module load braker/2.1.5
module load perl/5.26.2
module load augustus/20200703-dd2dd8f
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.1
module load samtools/1.8
module load GeneMark/4.62-es

module load cdbfasta
module load diamond
module load perl_modules
module load biopython

# Script
# Data retrival ln -s /proj/g2021012/2_Eckalbar_2016/additional_data/sel4_NW_015503979.fna.gz /home/viktosd/Genome_Analysis/ViktorSade_GenomeAnalysis/data/wgs_assembly/
# Ran in home/viktosd directory
cd /home/mama5390
source $AUGUSTUS_CONFIG_COPY
chmod a+w -R /home/mama5390/augustus_config/species/
cd /home/mama5390/genome_analysis/genome_analysis/scripts/
# cp -vf /sw/bioinfo/GeneMark/4.33-es/snowy/gm_key $HOME/.gm_key
# gunzip -f /home/viktosd/Genome_Analysis/ViktorSade_GenomeAnalysis/data/wgs_assembly/sel4_NW_015503979.fna.gz


export GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy

braker.pl --species=M.natalensis --genome=/home/mama5390/genome_analysis/data/raw_data/wgs/sel3_NW_015504249.fna --bam=/home/mama5390/genome_analysis/genome_analysis/out_files/star_alignment/star_alignment_refAligned.sortedByCoord.out.bam --AUGUSTUS_CONFIG_PATH=/home/mama5390/augustus_config --AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin --AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/scripts --GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy --min_contig=500 --useexisting
