#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:10:00
#SBATCH -J quality_control
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se

for i in /proj/g2021012/2_Eckalbar_2016/additional_data/GCF_001595765.1_Mnat.v1_genomic.gff.gz
do
  		ln -s $i ~/genome_analysis/data/raw_data/gff/
done
