#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:10:00
#SBATCH -J quality_control
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se

for i in /proj/g2021012/2_Eckalbar_2016/sel3/wgs_data/*
do
  		ln -s $i ~/genome_analysis/genome_analysis/raw_data/wgs/
done
