#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:10:00
#SBATCH -J quality_control
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se


# Load modules
module load bioinfo-tools
module load quast

#commands
python sw/apps/bioinfo/quast/5.0.2/rackham/bin/quast.py home/mama5390/genome_analysis/genome_analysis/out_files/assemble_wgs/graph_prefix.scafSeq


