#!/bin/bash -l

#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 06:00:00
#SBATCH -J align_rna
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se


# Load modules
module load bioinfo-tools
module load gcc star

# commands
#STAR --runThreadN 2 --runMode genomeGenerate --genomeDir ~/genome_analysis/genome_analysis/out_files/assembled_genome_index --genomeFastaFiles ~/genome_analysis/genome_analysis/out_files/assemble_wgs/graph_prefix.scafSeq --genomeChrBinNbits 11 --genomeSAindexNbases 13

STAR --genomeDir /home/mama5390/genome_analysis/genome_analysis/out_files/assembled_genome_index --runThreadN 2 --readFilesCommand gunzip -c  --readFilesIn /home/mama5390/genome_analysis/genome_analysis/out_files/trimmomatic_rna_seq/sel3_SRR1719266_1U.fq.gz,/home/mama5390/genome_analysis/genome_analysis/out_files/trimmomatic_rna_seq/sel3_SRR1719266_1P.fq.gz,/home/mama5390/genome_analysis/genome_analysis/out_files/trimmomatic_rna_seq/sel3_SRR1719266_1U.fq.gz,/home/mama5390/genome_analysis/genome_analysis/out_files/trimmomatic_rna_seq/sel3_SRR1719266_2P.fq.gz,/home/mama5390/genome_analysis/genome_analysis/out_files/trimmomatic_rna_seq/sel3_SRR1719266_2U.fq.gz --outFileNamePrefix /home/mama5390/genome_analysis/genome_analysis/out_files/star_alignment --outSAMtype BAM Unsorted 

