#!/bin/bash -l

#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:05:00
#SBATCH -J align_rna
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se

#HEJ=h2j
#echo $HEJ

for file in /home/mama5390/genome_analysis/data/raw_data/rna_seq/trimmed/P/*; do
echo $file  
file_prefix=${file%%.trim*}
echo $file_prefix
echo $file_prefix.trim
done

