#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:40:00
#SBATCH -J trim_data
#SBATCH --mail-type=ALL
#SBATCH --mail-user matilda.maxwell.5390@student.uu.se


# Load modules
module load bioinfo-tools
module load trimmomatic
# commands

cd ~/genome_analysis/genome_analysis/out_files/trimmomatic_rna_seq

java -jar /sw/apps/bioinfo/trimmomatic/0.36/rackham/trimmomatic-0.36.jar PE ~/genome_analysis/genome_analysis/data/raw_data/rna_seq/sel3_SRR1719266.1.fastq.gz ~/genome_analysis/genome_analysis/data/raw_data/rna_seq/sel3_SRR1719266.2.fastq.gz sel3_SRR1719266_1P.fq.gz sel3_SRR1719266_1U.fq.gz sel3_SRR1719266_2P.fq.gz sel3_SRR1719266_2U.fq.gz ILLUMINACLIP:/sw/bioinfo/trimmomatic/0.36/rackham/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

